export enum LandmarkType {
  LIBRARY = 'library',
  PARK = 'park',
  COMMUNITY_CENTER = 'community_center',
  CCF = 'cc_family',
  CCC = 'cc_centers',
  CA = 'ca',
  CBR = 'cbr',
  CD = 'cd',
  CT = 'ct',
  CO = 'co',
  CW = 'cw',
  LEAD0= 'lead0',
  LEAD1= 'lead1',
  LEAD2= 'lead2',
  LEAD3= 'lead3',
  LEAD4= 'lead4',
  LEAD5= 'lead5',
  LEAD6= 'lead6',
  COVIDVACC= 'covidvacc',
  COVIDCASE= 'covidcase',

}
